name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d726426b1866e075941daf232d1cb68fe8abab92ddb2f9da135f11a2501b564"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
