name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e207976f76d463b58cc64c622782beedeabfb544ea4efdb0ee21d0f7429e568f"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
