name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45c586df294444da3cd0513008c6414e1814a4c94b02448bee786f66c6d4c648"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
