name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55227a5f303dcf09608838b218e217fc2ffdcee38fb24a7c2c29b52082459d16"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
