name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8148c8a9aea2735352ce001af66fe3ed5afa228e02afa965e65a9d5d8a9c5f4e"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
