name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d6f94760f017dd56de6fd816c8532c4db15c5be2a1d467cf64af366188dba51"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
