name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1f5312b939976104aa2ee72a8ac6e042fcae77f42319f47833e9eeed36b131c"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
