name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87213197e6fcd4e2e8261c65ec34cd08fd6f06dd079136cde29066fb569a6a93"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
