name = "Groveborne"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de4477f52706eca32b33aa960c3f6f9d80d14d8edd24c92dba410c9efbf744ad"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
